### ISSUE TITLE
Cannot add new roles to the user

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#108]
![image](https://i.gyazo.com/61031c58c9cfa7d72feec5cc3bb863f0.gif)
Since unlike other user generated enums. The roles enum does not have a migration value. This should be changed.

**Comment by sorenbs** [comment]
The issue turned out to be in the dashboard.

The situation is like this: the enum list is not required. When you update the field (could be adding an enum value, changing the name or anything else) the mutation also sets the field required. This fails because there is existing data in the table and no default value is supplied.

I did some experiments, and this is the case for all scalar lists, not just enums or the roles field.

![image](https://cloud.githubusercontent.com/assets/281337/17510668/332a51a4-5e20-11e6-98d6-1ab6de62deb8.png)

**Comment by schickling** [comment]
So the bug is that the dashboard sets `isRequired` to true.
