### ISSUE TITLE
Project Settings - Reset Project Data and Models

### ISSUE THREAD

**Issue by aarmand** [graphcool/dashboard#220]
Seems to be hangup on resetting project data and models. Its been about 10 minutes and im still getting the round 'in progress' indicator. Post and Comment Models still show entries as well. Noting in case this is not expected.
![graphcool7](https://cloud.githubusercontent.com/assets/2370391/18874667/d95a6528-84c2-11e6-9574-d6d66225379b.PNG)

**Comment by sorenbs** [comment]
Hi @aarmand This is certainly not expected behaviour. The schema cache for your project was not correctly cleared when you reset the project. I have manually refreshed and am investigating why this didn't happen automatically.

Please reload the dashboard and the issue should be resolved.

Thanks for reporting this!
