### ISSUE TITLE
Can't specify relation as compulsory

### ISSUE THREAD

**Issue by sedubois** [graphcool/dashboard#234]
As the [doc](https://docs.graph.cool/guides/declaring-relations-between-your-models) on relations shows, after creating a `PostComment` relation, there is no way to ensure that `Comment`s have a non-null `Post`. Like in models, relations should have the possibility to specify a non-null constraint.

**Comment by sorenbs** [comment]
I just want to provide a bit of context: We previously decided against allowing relations to be marked as required because most of the cases we encountered where this would make sense are recursive in a way that would make it impossible to create the nodes in the first place. Consider the Case of a User model and a ProfilePicture model. Both models require the other, but as you have to create one node first and then the other, you won't be able to satisfy the non-null constraint.

We are currently enhancing the create mutation to allow you to create two or more related nodes in a single mutation. In addition to being really convenient it also solves this issue, so when this new feature is released I think we should also enable non-null constraints for relations.

Thanks for bringing this up!

**Comment by sedubois** [comment]
Great, looking forward to it 😊 IMHO, striving for database integrity is a Good Thing.

**Comment by schickling** [comment]
Moved this to here: https://github.com/graphcool/feature-requests/issues/12
