### ISSUE TITLE
Support for ListCells instead of a JSON input

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#38]
Currently, Enum or DateTime typed lists are not supported in the data browser.

**Comment by marktani** [comment]
For [Enum], currently empty lists in the add field cell are converted to the empty string in the mutation instead of the empty list. Also we have to use ["ADMIN"] at the moment to make it use instead of [ADMIN].

**Comment by sorenbs** [comment]
It also seems like [A,B] is converted to A in the mutation.

And updating an enum list field doesn't do anything usefull at all

**Comment by schickling** [comment]
@brene suggested that we change the way how we work with list values in general and rather re-use the functionality we have for the individual cells for lists as well.

@julianbauer do you have any idea how that could work in terms of UX/UI?

**Comment by brene** [comment]
- [ ] int and float edit fields are wrongly sized
- [ ] string and default field are fullscreen
- [ ] DateTime edit cell is full screen, can be toggled but not saved
- [ ] Setting Enum just throws a null error
- [ ] Generally, values can't be added by directly clicking on the "+" due to "onBlur" problem
- [ ] Boolean values aren't shown correctly after being added

**Comment by brene** [comment]
@julianbauer can you help me out with your css skills on this one? I can't make the DateTime field correctly formatted to let in appear correct on List field and on the normal cells
